In [2]:
import os
os.chdir('../')

In [5]:
os.listdir()

['classification',
 'dataset_manager.py',
 'main.ipynb',
 '.DS_Store',
 'LICENSE',
 'requirements.txt',
 'environment.yml',
 'util.py',
 'Makefile',
 'polluters',
 'metadata.json',
 '__pycache__',
 'README.md',
 'experiment.py',
 'main.py',
 'data',
 'notebooks']

In [7]:

from typing import List
import pandas as pd
from polluters import Polluter, FeatureAccuracyPolluter

In [9]:
df = pd.read_csv("data/clean/TelcoCustomerChurn.csv")

In [10]:
df

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,No,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No
7039,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,Yes,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No
7040,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,No,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes
7042,Male,0,No,No,66,Yes,No,Fiber optic,Yes,No,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No

In [11]:
def pollute(df: pd, polluters: List[Polluter]) -> pd.DataFrame:
    for polluter in polluters:
        df = polluter(df)
    return df

In [12]:
polluters = [FeatureAccuracyPolluter()]

TypeError: __init__() missing 3 required positional arguments: 'pollution_levels', 'categorical_cols', and 'numerical_cols'

In [6]:
df = pollute(df, polluters)

In [7]:
df

    sepal.length  sepal.width  petal.length  petal.width variety
22           4.6          3.6           1.0          0.2  Setosa